### ISSUE TITLE
Enhance documentation for API samples

### ISSUE THREAD

**Issue by mikezm** [ReachmailInc/WebAPISamples#5]
Documentation is lacking for the ReachMail API. Or at least not obvious enough for some people. Frankly, I've heard both sides. Some clients say the documentation is easy to follow, others can't even produce the JSON on request and instead provide an entire script and ask us to 'fix it'. I've listed some issues that have I've heard when dealing with clients. Perhaps with more obvious documentation, we could reduce issues. Some of these are already documented in the ZD help center, but perhaps we need to make it easier to find.
#### List of regular API issues:
- Clients don't know where to start
- Clients use acct_key instead of account_id (UUID).
- Do not know to check http_status responses for additional insight (php users mostly)
#### List of things we might be able to do to reduce these problems.
- [ ] Create a flow chart (visual) for sending a mailing (end to end)
- [ ] Add language independent examples to services.reachmail.net documentation page
  - could be in JSON format. URI, JSON, and Response. 
- [ ] Add link to support post on getting started with the API to the services.reachmail.net documentation page
- [x] language specific examples for: (could be added to ZD documentation system. Linked to from documentation pages.
  - [ ] uploading a list
  - [ ] adding a recipient
  - [ ] uploading a mailing
  - [ ] Scheduling a mailing
  - [ ] pulling report data
- [x] normalize function names across all API wrappers. This would allow us to reference a single function name when writing documentation. 

@danielsen, @ggulik, @nickemitchell24 please add comments as necessary.

**Comment by mikeobrien** [comment]
As Steve Jobs [said](https://www.youtube.com/watch?v=CW0DUg63lqU): "good artists copy; great artists steal": https://apidocs.mailchimp.com/

On normalizing function names, this would be difficult to do since there are a few ways to approach wrapper design. What is idiomatic in one language would be really awkward in another. So even though it might be nice from a support standpoint to normalize them it might suck from a coding perspective. Like using GTK in windows.

**Comment by danielsen** [comment]
Are the language-specific and cURL examples in the documentation not enough? I know we still need to do them for Python and PHP (ick) but using them is a matter of copy/paste and replacing some variables. Do the clients need more than this?

**Comment by Grummle** [comment]
So I recently took a look at this from the standpoint of our canadates. If
you just say here is an API use it, my biggest feeling is that the RM
concepts are missing. You'd have to use the RM UI to understand the
overview of making a mailing.

What is a list, what kinds of lists are there. What does each mean.
List upload general outline is create a csv, upload to data then call list
endpoint
What is a message, what kinds are there yada

A campaign is a list(s) and a message and a scheduled time for it to go out.

Basically over view stuff. After that if you can't figure how to use the
endpoints its on you. The examples and paramater information for each
individual endpoint is pretty good IMO



On Thu, Jan 15, 2015 at 3:52 PM, Dan Nielsen <notifications@github.com>
wrote:

> Are the language-specific and cURL examples in the documentation not
> enough? I know we still need to do them for Python and PHP (ick) but using
> them is a matter of copy/paste and replacing some variables. Do the clients
> need more than this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReachmailInc/WebAPISamples/issues/5#issuecomment-70169144>
> .
>



-- 
Michael Dillon
Developer

email | delivered
_______________________________________________________________
REACHMAIL Inc.  |  Main  888-947-3224   | 180 W Adams  |  Suite 800  |
 Chicago,
IL 60603
mdillon@reachmail.com  |  Direct 312-229-0124  |  http://www.reachmail.com

**Comment by mikeobrien** [comment]
Yeah, we really need to fill in the docs. It's just stubbed out ATM which like you said only gets you so far.

We have the ability to add content all over the place as demonstrated [here](http://www.mikeobrien.net/FubuMVC.Swank/#Administration@Users). So for stuff like @Grummle was mentioning we can add content at the [module](https://github.com/ReachmailInc/Reachmail/blob/master/src/Reachmail.Web.ServiceHost/Lists/Module.md) or [resource](https://github.com/ReachmailInc/Reachmail/blob/master/src/Reachmail.Web.ServiceHost/Lists/Resource.md) level.

**Comment by mikeobrien** [comment]
About time!
