### ISSUE TITLE
.NET Wrapper Missing Data.Get

### ISSUE THREAD

**Issue by austinjordanFA** [ReachmailInc/WebAPISamples#8]
Apologies if duplicate report (working with Mike Marshall via email).

Documentation states:
http://services.reachmail.net/#Data@/data
'var reachmail = Reachmail.Api.Create("<API Token>");
var dataId = Guid.Parse("00000000-0000-0000-0000-000000000000");
var result = reachmail.Data.Get(dataId);'

However, Data.Get method is missing from the C# Wrapper
![image](https://cloud.githubusercontent.com/assets/2153604/9890943/e35958e8-5bb7-11e5-8b7f-90b4b4ace1d0.png)
![image](https://cloud.githubusercontent.com/assets/2153604/9890948/e7217afa-5bb7-11e5-9496-47e0946fc484.png)

**Comment by alexmaris** [comment]
Hi Austin - which version of the wrapper are you using? The 2.0.0.47 version that's available on NuGet should have a Reachmail.Data.Get method; can you check if a package update is available for your solution (PM> Get-Package -updates)?

**Comment by austinjordanFA** [comment]
@alexmaris strange, I'm using 2.0.0.47... (no package update available)
![image](https://cloud.githubusercontent.com/assets/2153604/9941267/060205f8-5d29-11e5-98bb-2546cf769376.png)

I tried un-installing, re-installing the package, same result. I also tried it in VS2012 and VS2015. Appears to be no Data.Get method
![image](https://cloud.githubusercontent.com/assets/2153604/9941388/d77935b6-5d29-11e5-8561-a535bd9797b0.png)

When you install in a project does it show you Data.Get in the object browser? I checked earlier versions too and it appeared to be missing. I understand it's just a wrapper for the actual API, and I could hit the API with a GET, etc.. but I really am enjoying the simplicity of the package =)

**Comment by alexmaris** [comment]
Ahh you're looking for a Data.Get object, which you're right, does not exist. The documentation states that there's a Get() method on the Reachmail.Api.Data property which returns a Stream.

**Comment by austinjordanFA** [comment]
@alexmaris I think I figured it out now =) Somehow I got confused with the documentation and how to create the RM.data.get method =/ Thanks for your help!

**Comment by alexmaris** [comment]
Great! Ping us if you have any questions or run into any other issues.
