### ISSUE TITLE
.NET - Export List timing out

### ISSUE THREAD

**Issue by mikezm** [ReachmailInc/WebAPISamples#9]
Austin Jordan (from Fresh Address who also opened ticket https://github.com/ReachmailInc/WebAPISamples/issues/8) is running into timeouts trying to export a list of 450K+

We've run into similar issues on the timeout with DD account when they use the other data service to import large lists. We were able to increase the timeout a bit then to accommodate. Hopefully we can do the same here. 

Here's what he had to say via email:
```I switched our code to use the Lists.Export method instead of using Recepients.Filtered so I could just download files instead, thinking it would handle larger lists more efficiently. However, I'm having the same underlying HttpClient timeout issue when trying to retrieve a large list. I can confirm it's working fine for smaller files, but when I try to create the export ID for a list of 450k+, I get a timeout (same problem I was having with Recepients.Filtered). If it was a one-off occurance I wouldn't bother with it, but I know we'll have large deployments in the future.```

![image](https://cloud.githubusercontent.com/assets/1086901/9960104/2c352092-5dde-11e5-8fc2-03be3dcb2af0.png)

```I believe I could address the issue by setting the timeout, but I can't because it's private:
Is it possible that the API could be expanded to deal with this issue? Allowing the timeout to be set inside the Reachmail API object?
Let me know if I can provide any more detail or information.```

https://github.com/ReachmailInc/WebAPISamples/blob/master/dotnet/Wrapper/Reachmail/HttpClient.cs#L33

**Comment by alexmaris** [comment]
A timeout can be set when instantiating an API or HttpClient object, ex: 
* var api = Api.Create("my_secret_toke", allowSelfSignedCerts: true, timeout: 1200) 
* var httpClient = new HttpClient(baseUrl, accountKey + @"\" + username, password, allowSelfSignedCerts, proxy, timeout);

We can expose the timeout property, if necessary, but the more elegant fix would be to define the timeout in the constructor ( default is 30 seconds).

**Comment by bkothe-rm** [comment]
Are there any drawbacks to allowing the user to define a timeout?  If we were to do this would it make sense to implement a max value for timeout?

**Comment by alexmaris** [comment]
I should have specified that the current wrapper allows for the timeout to be set via a constructor (defined in seconds); we wouldn't be breaking functionality by exposing the timeout property, the next Get/Execute method call would use the new timeout value. I do prefer setting it via a constructor only though, looks a bit cleaner to me (less mutable).

Behind the scenes we rely on HttpWebRequest, which lets you get/set the timeout prop (in milliseconds though).
